---
- hosts: ubuntu_servers
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - include_role:
        name: configure_network
    - include_role:
        name: configure_proxy
    - include_role:
        name: install_packages
    - include_role:
        name: install_zabbix_agent
    # - include_role:
        # name: install_exacqvision
    - name: Set root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"
        update_password: always
